#ifndef LV_CONF_H
#define LV_CONF_H

#define LV_COLOR_DEPTH 16

#define LV_FONT_MONTSERRAT_8  0
#define LV_FONT_MONTSERRAT_10 0
#define LV_FONT_MONTSERRAT_12 1
#define LV_FONT_MONTSERRAT_14 1
#define LV_FONT_MONTSERRAT_16 1
#define LV_FONT_MONTSERRAT_18 1
#define LV_FONT_MONTSERRAT_20 1
#define LV_FONT_MONTSERRAT_22 1
#define LV_FONT_MONTSERRAT_24 1
#define LV_FONT_MONTSERRAT_26 1
#define LV_FONT_MONTSERRAT_28 1
#define LV_FONT_MONTSERRAT_30 1
#define LV_FONT_MONTSERRAT_32 1
#define LV_FONT_MONTSERRAT_34 1
#define LV_FONT_MONTSERRAT_36 1
#define LV_FONT_MONTSERRAT_38 1
#define LV_FONT_MONTSERRAT_40 1
#define LV_FONT_MONTSERRAT_42 1
#define LV_FONT_MONTSERRAT_44 1
#define LV_FONT_MONTSERRAT_46 1
#define LV_FONT_MONTSERRAT_48 1

#define LV_USE_FONT_MONTSERRAT_12 1
#define LV_USE_FONT_MONTSERRAT_14 1
#define LV_USE_FONT_MONTSERRAT_16 1
#define LV_USE_FONT_MONTSERRAT_18 1
#define LV_USE_FONT_MONTSERRAT_20 1
#define LV_USE_FONT_MONTSERRAT_22 1
#define LV_USE_FONT_MONTSERRAT_24 1
#define LV_USE_FONT_MONTSERRAT_26 1
#define LV_USE_FONT_MONTSERRAT_28 1
#define LV_USE_FONT_MONTSERRAT_30 1
#define LV_USE_FONT_MONTSERRAT_32 1
#define LV_USE_FONT_MONTSERRAT_34 1
#define LV_USE_FONT_MONTSERRAT_36 1
#define LV_USE_FONT_MONTSERRAT_38 1
#define LV_USE_FONT_MONTSERRAT_40 1
#define LV_USE_FONT_MONTSERRAT_42 1
#define LV_USE_FONT_MONTSERRAT_44 1
#define LV_USE_FONT_MONTSERRAT_46 1
#define LV_USE_FONT_MONTSERRAT_48 1


#define LV_USE_IMAGE 1

#endif